import { Containers } from './containerTypes'

// https://ekosystem.wroc.pl/segregacja-odpadow/gdzie-wrzucic/?odpad=materac
export const garbages = [
    { name: 'Puszka', container: Containers.PLASTICANDMETALS },
    { name: 'Folia aluminiowa', container: Containers.PLASTICANDMETALS },
    { name: 'Kapsel', container: Containers.PLASTICANDMETALS },
    { name: 'Baterie', container: Containers.DANGEROUS },
    { name: 'Akumulator samochodowy', container: Containers.DANGEROUS },
    { name: 'Elektronika', container: Containers.ELECTRONIC },
    { name: 'Telefon', container: Containers.ELECTRONIC },
    { name: 'Materiały budowlane', container: Containers.OTHER },
    { name: 'Materac', container: Containers.HUGEWASTES },
    { name: 'Łożko', container: Containers.HUGEWASTES },
    { name: 'Szafa', container: Containers.HUGEWASTES },
    { name: 'Biurko', container: Containers.HUGEWASTES },
    { name: 'Plastikowe zabawki', container: Containers.MIXED },
    { name: 'Opakowanie po jajkach', container: Containers.PAPER },
    { name: 'Czasopismo', container: Containers.PAPER },
    { name: 'Ulotka', container: Containers.PAPER },
    { name: 'Papier', container: Containers.PAPER },
    { name: 'Karton', container: Containers.PAPER },
    { name: 'Tektura', container: Containers.PAPER },
    { name: 'Pudełko po pizzy', container: Containers.PAPER },
    { name: 'Rurka po papierze toaletowym', container: Containers.PAPER },
    { name: 'Rurka po ręczniku kuchennym', container: Containers.PAPER },
    { name: 'NIeotłuszczona torba papierowa', container: Containers.PAPER },
    { name: 'Otłuszczona torba papierowa', container: Containers.MIXED },
    { name: 'Zeszyt', container: Containers.PAPER },
    { name: 'Brudny papier', container: Containers.MIXED },
    { name: 'Zużyte chusteczki', container: Containers.MIXED },
    { name: 'Zużyty ręcznik papierowy', container: Containers.MIXED },
    { name: 'Worek po nawozie', container: Containers.MIXED },
    { name: 'Worek po materiałach budowlanych', container: Containers.MIXED },
    { name: 'Paragon', container: Containers.MIXED },
    { name: 'Okładka książki', container: Containers.MIXED },
    { name: 'Książka (bez okładki)', container: Containers.PAPER },
    { name: 'worek foliowy', container: Containers.PLASTICANDMETALS },
    { name: 'Zatłuszczony worek foliowy', container: Containers.MIXED },
    { name: 'reklamowka', container: Containers.PLASTICANDMETALS },
    { name: 'Kartonowe opakowanie', container: Containers.PAPER, additionalInfo: 'Jeśli to możliwe, z kartonowych paczek usuwamy taśmę klejącą i wyrzucamy ją do odpadów zmieszanych' },
    { name: 'Folia', container: Containers.PLASTICANDMETALS },
    { name: 'Zatłuszczona folia', container: Containers.MIXED },
    { name: 'Pusty słoik bez pokrywki', container: Containers.GLASS },
    { name: 'Pusta plastikowa butelka', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby ją zgnieść przed wyrzuceniem' },
    { name: 'Butelka po oleju silnikowym', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby ją zgnieść przed wyrzuceniem' },
    { name: 'Nakrętka', container: Containers.PLASTICANDMETALS, additionalInfo: 'Powinna być oddzielona od butelki' },
    { name: 'Karton po mleku', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby zgnieść karton przed wyrzuceniem, opakowanie powinno być puste' },
    { name: 'Karton po soku', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby zgnieść karton przed wyrzuceniem, opakowanie powinno być puste' },
    { name: 'Butelka po szamponie', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby zgnieść butlekę przed wyrzuceniem, opakowanie powinno być puste' },
    { name: 'Butelka po środkach czystości', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby zgnieść butlekę przed wyrzuceniem, opakowanie powinno być puste' },
    { name: 'Tubka po paście do zębów', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby zgnieść tubkę przed wyrzuceniem, opakowanie powinno być puste' },
    { name: 'Puszka', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby zgnieść puszkę przed wyrzuceniem, opakowanie powinno być puste' },
    { name: 'Zakrętki od słoików', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Nakrętki od słoików', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Folia aluminiowa', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Zatłuszczony folia aluminiowa', container: Containers.MIXED },
    { name: 'Folia opakowaniowa', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Foliowa saszetka po jedzeniu', container: Containers.PLASTICANDMETALS, additionalInfo: 'Opakowanie powinno być puste' },
    { name: 'Foliowa saszetka po kosmetykach', container: Containers.PLASTICANDMETALS, additionalInfo: 'Opakowanie powinno być puste' },
    { name: 'Garnek', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Patelnia', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Koperta z folią bombelkową', container: Containers.PLASTICANDMETALS, additionalInfo: 'Oddzielić papier i wrzucić go do pojemnika na papier' },
    { name: 'Kapsułki po kawie', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Opakowanie po jogurcie', container: Containers.PLASTICANDMETALS, additionalInfo: 'Pamiętaj aby zgnieść opakowanie przed wyrzuceniem, opakowanie powinno być puste' },
    { name: 'Styropian', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Woreczek foliowy', container: Containers.PLASTICANDMETALS, additionalInfo: '' },
    { name: 'Warzywa', container: Containers.BIO },
    { name: 'Owoce', container: Containers.BIO },
    { name: 'Mięso', container: Containers.MIXED },
    { name: 'Opakowanie po ', container: Containers.MIXED },
    { name: 'Butla gazowa', container: Containers.OTHER },
    { name: 'Opakowanie po aerozolu', container: Containers.PLASTICANDMETALS },
    { name: 'Opakowanie po farbie', container: Containers.SELECTIVEWASTES },
    { name: 'Płyty CD / DVD', container: Containers.SELECTIVEWASTES },
    { name: 'AGD', container: Containers.ELECTRONIC },
    { name: 'RTV', container: Containers.ELECTRONIC },
    { name: 'Telewizor', container: Containers.ELECTRONIC },
    { name: 'Lodówka', container: Containers.ELECTRONIC },
    { name: 'Pralka', container: Containers.ELECTRONIC },
    { name: 'Plastikowa butelka', container: Containers.PLASTICANDMETALS },
    { name: 'Części roślin', container: Containers.BIO },
    { name: 'Fusy z kawy', container: Containers.BIO },
    { name: 'Fusy z herbaty', container: Containers.BIO },
    { name: 'Owoce', container: Containers.BIO },
    { name: 'Jajka', container: Containers.BIO },
    { name: 'Siano', container: Containers.BIO },
    { name: 'Trociny', container: Containers.BIO },
    { name: 'Warzywa', container: Containers.BIO },
    { name: 'Zepsute jedzenie (bez mięsa lub tłuszczu)', container: Containers.BIO },
    { name: 'Zepsute jedzenie zawierające mięso', container: Containers.MIXED },
    { name: 'Ziemia', container: Containers.MIXED },
    { name: 'Kamienie', container: Containers.MIXED },
    { name: 'Popiół', container: Containers.MIXED },
    { name: 'Drewno', container: Containers.MIXED },
    { name: 'Drewno', container: Containers.MIXED },
    { name: 'Kości', container: Containers.MIXED },
    { name: 'Mięso', container: Containers.MIXED },
    { name: 'Odchody zwierząt', container: Containers.MIXED },
    { name: 'Olej jadalny', container: Containers.MIXED },
    { name: 'Kurz', container: Containers.MIXED },
    { name: 'Szklana butelka po napoju', container: Containers.GLASS, additionalInfo: 'Opakowanie powinno być puste' },
    { name: 'Szklane opakowanie po kosmetykach', container: Containers.GLASS, additionalInfo: 'Opakowanie powinno być puste' },
    { name: 'Przeterminowane kosmetyki w plastikowej butelce', container: Containers.MIXED, additionalInfo: '' },
    { name: 'Przeterminowane kosmetyki w szklanej butelce', container: Containers.MIXED, additionalInfo: '' },
    { name: 'Ceramika', container: Containers.SELECTIVEWASTES },
    { name: 'Doniczka szklana', container: Containers.OTHER },
    { name: 'Porcelana', container: Containers.MIXED },
    { name: 'Opakowania po dezodorancie (oznaczone do recyklingu)', container: Containers.PLASTICANDMETALS },
    { name: 'Kask narciarski', container: Containers.MIXED },
    { name: 'Gąbka do naczyń', container: Containers.MIXED },
  ]